<?
if($edp_relative_path==="../") {
    if(!include_once "../admin/language/language_".$lang.".php") {include_once "../admin/language/language_us.php";}
} else {
    if(!include_once "../../admin/language/language_".$lang.".php") {include_once "../../admin/language/language_us.php";}
}
if ($action=="logout") { session_unregister("Stoitsov"); unset($Stoitsov); }
if ($action=="reg_user") { unset($Error); if (strlen(puHackers($puUsername))<1) $Error.="<b>".$language['Username is invalid. Min 1 character'].".</b><br>"; if (strlen(puHackers($puPassword))<4) $Error.="<b>".$language['Password is invalid. Min 4 chars'].".</b><br>";if (strlen(puHackers($puScreenName))<5) $Error.="<b>".$language['Screen Name is invalid. Min 5 chars'].".</b><br>"; if (strlen(puHackers($puMail))<1) $Error.="<b>".$language['E-mail is empty. Must supply valid e-mail'].".</b><br>"; if (isset($Error)) { $page="register"; $do="reg_user"; $puID=="";} else { if($puID=="") {puMyQuery("INSERT INTO edp_puusers VALUES(null,'".puHackers($puUsername)."','".puHackers($puPassword)."','".puHackers($puScreenName)."','".puHackers($puMail)."','".puHackers($puAdmin)."');"); $puID=mysql_insert_id();} $page="register"; } }
if ($action=="edit_reg_user") {unset($Error);if (strlen(puHackers($puUsername))<1) $Error.="<b>".$language['Username is invalid. Min 1 character'].".</b><br>";if (strlen(puHackers($puPassword))<4) $Error.="<b>".$language['Password is invalid. Min 4 chars'].".</b><br>";if (strlen(puHackers($puScreenName))<5) $Error.="<b>".$language['Screen Name is invalid. Min 5 chars'].".</b><br>";if (strlen(puHackers($puMail))<1) $Error.="<b>".$language['E-mail is empty. Must supply valid e-mail'].".</b><br>";if (isset($Error)) { $page="users"; $do="edit_user"; $id=$puID; } else {puMyQuery("UPDATE edp_puusers SET puUsername='".puHackers($puUsername)."', puPassword='".puHackers($puPassword)."', puScreenName='".puHackers($puScreenName)."', puMail='".puHackers($puMail)."', puAdmin='".puHackers($puAdmin)."' WHERE ID=$puID;"); $page="register";} }
if ($action=="add_user") { if (puRegistered($Stoitsov)!=2) { $page="login"; $Error="<b>".$language['You need to be an administrator to use this function'].".</b><br>"; } else {unset($Error);if (strlen(puHackers($puUsername))<1) $Error.="<b>".$language['Username is invalid. Min 1 character'].".</b><br>";if (strlen(puHackers($puPassword))<4) $Error.="<b>".$language['Password is invalid. Min 4 chars'].".</b><br>";if (strlen(puHackers($puScreenName))<5) $Error.="<b>".$language['Screen Name is invalid. Min 5 chars'].".</b><br>";if (strlen(puHackers($puMail))<1) $Error.="<b>".$language['E-mail is empty. Must supply valid e-mail'].".</b><br>";if (isset($Error)) { $page="users"; $do="add_user";} else { puMyQuery("INSERT IGNORE INTO edp_puusers VALUES(null,'".puHackers($puUsername)."','".puHackers($puPassword)."','".puHackers($puScreenName)."','".puHackers($puMail)."','".puHackers($puAdmin)."');"); $page="users";} } }
if ($action=="edit_user") {if (puRegistered($Stoitsov)!=2) { $page="login"; $Error="<b>".$language['You need to be an administrator to use this function'].".</b><br>"; } else {unset($Error);if (strlen(puHackers($puUsername))<1) $Error.="<b>".$language['Username is invalid. Min 1 character'].".</b><br>";if (strlen(puHackers($puPassword))<4) $Error.="<b>".$language['Password is invalid. Min 4 chars'].".</b><br>";if (strlen(puHackers($puScreenName))<5) $Error.="<b>".$language['Screen Name is invalid. Min 5 chars'].".</b><br>";if (strlen(puHackers($puMail))<1) $Error.="<b>".$language['E-mail is empty. Must supply valid e-mail'].".</b><br>";if (isset($Error)) { $page="users"; $do="edit_user"; $id=$puID; } else {puMyQuery("UPDATE edp_puusers SET puUsername='".puHackers($puUsername)."', puPassword='".puHackers($puPassword)."', puScreenName='".puHackers($puScreenName)."', puMail='".puHackers($puMail)."', puAdmin='".puHackers($puAdmin)."' WHERE ID=$puID;"); $page="users";} } }
if ($action=="login") { $Check=puMyQuery("SELECT ID, puUsername, puScreenName, puAdmin FROM edp_puusers WHERE BINARY puUsername='".puHackers($puUsername)."' AND BINARY puPassword='".puHackers($puPassword)."' LIMIT 1;"); if (mysql_num_rows($Check)!=0) { $Stoitsov=mysql_fetch_array($Check); session_register("Stoitsov"); } else {$Error="<b>".$language['Invalid username or password'].".</b><br>"; $page="login";} }
// if ($action=="login") { $Error="<h1>Disabled in this tryial version</h1>"; $page="login"; }
?>
